name: DEX2C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      NDK_VERSION: r25b
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache NDK
      id: cache-ndk
      uses: actions/cache@v3
      with:
        path: ~/android-ndk
        key: ndk-${{ env.NDK_VERSION }}

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk dx unzip
        
    - name: Install NDK (if not cached)
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/android-ndk
        curl -L https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip -o ndk.zip
        unzip -q ndk.zip -d ~/android-ndk
        mv ~/android-ndk/android-ndk-${{ env.NDK_VERSION }} ~/android-ndk/ndk
        
    - name: Run conversion
      run: |
        python dcc.py -i classes.dex -f filter.txt -o out/ \
          --ndk-path ~/android-ndk/ndk \
          --dynamic-register -v
        
    - name: Verify outputs
      run: |
        ls -R out/
        [ -f out/modified.dex ] || exit 1
        [ -d out/libs ] || exit 1
        find out/libs -name "*.so" | xargs ls -lh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dex2c-output
        path: out
