name: DEX2C Conversion
on: [push, pull_request]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install androguard asn1crypto pyasn1 pyasn1-modules
        
    - name: Run conversion
      run: |
        python dcc.py -i classes.dex -f filter.txt -o out/
        
    - name: Verify output
      run: |
        [ -f out/modified.dex ] || exit 1
        [ -f out/jni/nc/*.cpp ] || exit 1
        echo "✓ Conversion successful"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dex2c-output
        path: out/
