name: DEX2C Build
on: [push, pull_request]

env:
  NDK_VERSION: r25b
  NDK_CACHE_KEY: ndk-${{ env.NDK_VERSION }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache NDK
      id: cache-ndk
      uses: actions/cache@v3
      with:
        path: ~/android-ndk
        key: ${{ env.NDK_CACHE_KEY }}

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk dx unzip
        
    - name: Install NDK (if not cached)
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/android-ndk
        curl -L https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip -o ndk.zip
        unzip -q ndk.zip -d ~/android-ndk
        mv ~/android-ndk/android-ndk-${{ env.NDK_VERSION }} ~/android-ndk/android-ndk
        
    - name: Set up paths
      run: |
        echo "NDK_DIR=$HOME/android-ndk/android-ndk" >> $GITHUB_ENV
        echo "$HOME/android-ndk/android-ndk" >> $GITHUB_PATH
        
    - name: Run conversion
      run: |
        python dcc.py -i classes.dex -f filter.txt -o out/ \
          --ndk-path $HOME/android-ndk/android-ndk \
          --dynamic-register -v
        
    - name: Verify outputs
      run: |
        [ -f out/modified.dex ] || { echo "Missing modified.dex"; exit 1; }
        [ -d out/libs ] || { echo "Missing libs directory"; exit 1; }
        echo "=== Generated .so files ==="
        find out/libs -name "*.so" | xargs ls -lh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dex2c-output
        path: |
          out/modified.dex
          out/libs/
          out/jni/nc/
