name: DEX2C Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install androguard
        sudo apt-get install -y dx  # For DEX manipulation tools

    - name: Set up Android NDK
      uses: android-actions/setup-android-ndk@v2
      with:
        ndk-version: '25b'  # Latest stable version

    - name: Run conversion (skip NDK build)
      run: |
        # Temporarily disable NDK build
        sed -i 's/if not run_ndk_build(project_dir):/if False:/' dcc.py
        python dcc.py -i classes.dex -f filter.txt -o out/
        
    - name: Verify output (DEX only)
      run: |
        [ -f out/modified.dex ] || exit 1
        [ -f out/jni/nc/*.cpp ] || exit 1
        echo "✓ DEX conversion successful"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dex2c-output
        path: out/
